### PR TITLE
Refactor multi output and add omniorbpy

### PR DESCRIPTION
**Pull request by beenje**
Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

Refactored the multi-output as current solution was quite fragile as pointed out in https://github.com/conda-forge/omniorb-feedstock/pull/46

Add `omniorbpy` as new output as discussed in https://github.com/conda-forge/gepetto-viewer-corba-feedstock/pull/22

This allows to:
- release both `omniorb` and `omniorbpy` at the same time
- make `omniorbpy` depends on the exact version of `omniorb`
- build `omniorbpy` on windows (it needs to be built from under `omniorb/src/lib`)

When merged, the https://github.com/conda-forge/omniorbpy-feedstock needs to be archived.

### CODE REVIEW

**Comment by beenje** [comment]
@conda-forge-admin, please rerender

**Comment by beenje** [comment]
@lockhart I refactored the recipe multi output and included `omniORBpy`.

I had issues compiling the ssl transport with the latest openssl. `configure` reported it found `openssl` but compilation was skipped. Issue was that `pkg-config --variable=prefix openssl` reports an empty string and that was used for `OPEN_SSL_ROOT`. I applied a small patch to use the `prefix` instead (in both `omniorb` and `omniorbpy`) and opened an issue in https://github.com/conda-forge/openssl-feedstock/issues/155

`omniorbpy` build still raises some warning about `omniorb-libs` not being in reqs/run. It is in host.
In run, we have `{{ pin_subpackage('omniorb', exact=True) }}`, which itself also as in run `{{ pin_subpackage('omniorb-libs', exact=True) }}`. I guess I could add it as well? 

@h-vetinari , as you contributed to this recipe before, I'd appreciate some review. If you have time of course.

**Comment by lockhart** [comment]
Oh great! I’ve started working on this but had a dearth of examples in the conda docs and conda feedstocks to see how to split this up.

Happy to drop my work and help with testing of this new version.

- Tom

**Review by h-vetinari — COMMENTED** [review]
I just skimmed the diff for a bit, but it looks like a very good effort. Well done!

(PS. I haven't really contributed here except helping various boost migrations)

**Comment by h-vetinari** [comment]
> `omniorbpy` build still raises some warning about `omniorb-libs` not being in reqs/run. It is in host.
> In run, we have `{{ pin_subpackage('omniorb', exact=True) }}`, which itself also as in run `{{ pin_subpackage('omniorb-libs', exact=True) }}`. I guess I could add it as well?

I don't know the exact reason why, but run-exports don't get applied in the recipe where they're being built. So you should add a run-dep for `{{ pin_subpackage('omniorb-libs', exact=True) }}`

**Comment by beenje** [comment]
@conda-forge-admin, please rerender

**Comment by beenje** [comment]
Pinging @conda-forge/omniorbpy explicitly as it impacts your feedstock.

I updated the feedstock to store artifacts on azure. To test, you can download them [here](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=936400&view=artifacts&pathAsName=false&type=publishedArtifacts)

**Comment by beenje** [comment]
@lockhart if you are happy with this PR, please approve and I will merge

**Review by lockhart — APPROVED** [review]
Combining omniorb and omniorbpy into a single package solves the problem of conda not recognizing unique micro-releases and having omniorbpy built against the previous version of omniorb. These changes have been tested on my Sonoma M3 laptop against a significant production app and all features passed.

**Comment by lockhart** [comment]
OK done just now. Sorry for dropping the ball on this.

- Tom

**Pull request merged**
