### PR TITLE
Improve package

### LINKED ISSUE #10: Add LGPL-2.1-or-later license too
- [x ] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:

OmniORB software is licensed under multiple licenses, GPL-2.0-or-later for the programs, LGPL-2.1-or-later for the libraries.
I think COPYING.LIB should also be specified in the list of [license_file metadata](https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#license-file) in the recipe.
I don't know how it works for the license metadata in the conda recipe. Can we specify a list of licenses here?
The conda-build documentation does not seem clear on that point.
If yes, I think it would be good to add LGPL-2.1-or-later to the list of licenses.

I think it would be also good to modify GPL-2.0-only to GPL-2.0-or-later too because the files in omniORB source code are specifying the "or later" option as you can see in the header of the following file:
- https://sourceforge.net/p/omniorb/svn/HEAD/tree/tags/4_2_4/omniORB/src/tool/omniidl/cxx/idltype.cc
or the following file to illustrate a file where LGPL2.1 or later license applies:
- https://sourceforge.net/p/omniorb/svn/HEAD/tree/tags/4_2_4/omniORBpy/include/omniORBpy.h

### PR DESCRIPTION
**Pull request by beenje**
Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

- Add LGPL license: Fix #10
- Make install more standard on windows. Remove x86_win32 from OMNI_RUNTIME_DESTINATION and OMNI_ARCHIVE_DESTINATION. If dll are installed under bin/x86_win32, they aren't found by default.
This is an issue for TangoTest for example.
- Move include to omniorb-libs. Allow to build pytango only depending on omniorb-libs (without forcing
the Python version that comes with omniorb).

### CODE REVIEW

**Comment by beenje** [comment]
@conda-forge-admin, please rerender

**Comment by beenje** [comment]
@t-b and @ajoubertza, I'd appreciate your input on those changes.

**Comment by t-b** [comment]
@beenje Looks good!

**Comment by ajoubertza** [comment]
@beenje Looks good.

**Pull request merged**
