### PR TITLE
Use official windows build

### LINKED ISSUE #37: windows marshalling issue
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

Hello,
It seems that there is a marshalling issue with 4.2.5 conda forge build (Windows 64bit).
More details in the following issue:
https://gitlab.com/tango-controls/cppTango/-/issues/1066
Thanks

### Installed packages

```shell
(base) N:\tango\pytango\jlptest>conda list
# packages in environment at C:\ProgramData\miniconda3:
#
# Name                    Version                   Build  Channel
boost                     1.78.0          py310h220cb41_4    conda-forge
boost-cpp                 1.78.0               h9f4b32c_1    conda-forge
brotlipy                  0.7.0           py310h2bbff1b_1002
bzip2                     1.0.8                he774522_0
ca-certificates           2022.12.7            h5b45459_0    conda-forge
certifi                   2022.12.7          pyhd8ed1ab_0    conda-forge
cffi                      1.15.1          py310h2bbff1b_3
charset-normalizer        2.0.4              pyhd3eb1b0_0
colorama                  0.4.6           py310haa95532_0
conda                     23.1.0          py310haa95532_0
conda-content-trust       0.1.3           py310haa95532_0
conda-package-handling    2.0.2           py310haa95532_0
conda-package-streaming   0.7.0           py310haa95532_0
console_shortcut_miniconda 0.1.1                haa95532_1
cpptango                  9.4.1                h643942d_0    conda-forge
cryptography              38.0.4          py310h21b164f_0
idna                      3.4             py310haa95532_0
intel-openmp              2023.0.0         h57928b3_25922    conda-forge
libblas                   3.9.0              16_win64_mkl    conda-forge
libcblas                  3.9.0              16_win64_mkl    conda-forge
libffi                    3.4.2                hd77b12b_6
libhwloc                  2.8.0                h039e092_1    conda-forge
libiconv                  1.17                 h8ffe710_0    conda-forge
libjpeg-turbo             2.1.4                hcfcfb64_1    conda-forge
liblapack                 3.9.0              16_win64_mkl    conda-forge
libsodium                 1.0.18               h8d14728_1    conda-forge
libxml2                   2.10.3               hc3477c8_0    conda-forge
libzlib                   1.2.13               hcfcfb64_4    conda-forge
menuinst                  1.4.19          py310h59b6b97_0
mkl                       2022.1.0           h6a75c08_874    conda-forge
numpy                     1.24.2          py310hd02465a_0    conda-forge
omniorb-libs              4.2.5                hb04206d_4    conda-forge
openssl                   1.1.1t               hcfcfb64_0    conda-forge
packaging                 23.0               pyhd8ed1ab_0    conda-forge
pip                       22.3.1          py310haa95532_0
pluggy                    1.0.0           py310haa95532_1
powershell_shortcut_miniconda 0.0.1                haa95532_1
psutil                    5.9.4           py310h8d17308_0    conda-forge
pthreads-win32            2.9.1                hfa6e2cd_3    conda-forge
pycosat                   0.6.4           py310h2bbff1b_0
pycparser                 2.21               pyhd3eb1b0_0
pyopenssl                 22.0.0             pyhd3eb1b0_0
pysocks                   1.7.1           py310haa95532_0
pytango                   9.4.0           py310hdd9df50_0    conda-forge
python                    3.10.9               h966fe2a_0
python_abi                3.10                    2_cp310    conda-forge
requests                  2.28.1          py310haa95532_0
ruamel.yaml               0.17.21         py310h2bbff1b_0
ruamel.yaml.clib          0.2.6           py310h2bbff1b_1
setuptools                65.6.3          py310haa95532_0
six                       1.16.0             pyhd3eb1b0_1
sqlite                    3.40.1               h2bbff1b_0
tbb                       2021.7.0             h91493d7_1    conda-forge
tk                        8.6.12               h2bbff1b_0
toolz                     0.12.0          py310haa95532_0
tqdm                      4.64.1          py310haa95532_0
tzdata                    2022g                h04d1e81_0
ucrt                      10.0.22621.0         h57928b3_0    conda-forge
urllib3                   1.26.14         py310haa95532_0
vc                        14.2                 h21ff451_1
vs2015_runtime            14.34.31931         h4c5c07a_10    conda-forge
wheel                     0.37.1             pyhd3eb1b0_0
win_inet_pton             1.1.0           py310haa95532_0
wincertstore              0.2             py310haa95532_2
xz                        5.2.10               h8cc25b3_1
zeromq                    4.3.4                h0e60522_1    conda-forge
zlib                      1.2.13               hcfcfb64_4    conda-forge
zstandard                 0.18.0          py310h2bbff1b_0
zstd                      1.5.2                h12be248_6    conda-forge
```

### Environment info

```shell
(base) N:\tango\pytango\jlptest>conda info

     active environment : base
    active env location : C:\ProgramData\miniconda3
            shell level : 3
       user config file : C:\Users\pons\.condarc
 populated config files :
          conda version : 23.1.0
    conda-build version : not installed
         python version : 3.10.9.final.0
       virtual packages : __archspec=1=x86_64
                          __cuda=11.1=0
                          __win=0=0
       base environment : C:\ProgramData\miniconda3  (writable)
      conda av data dir : C:\ProgramData\miniconda3\etc\conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\ProgramData\miniconda3\pkgs
                          C:\Users\pons\.conda\pkgs
                          C:\Users\pons\AppData\Local\conda\conda\pkgs
       envs directories : C:\ProgramData\miniconda3\envs
                          C:\Users\pons\.conda\envs
                          C:\Users\pons\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/23.1.0 requests/2.28.1 CPython/3.10.9 Windows/10 Windows/10.0.19045
          administrator : True
             netrc file : None
           offline mode : False
```

### PR DESCRIPTION
**Pull request by beenje**
Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

Drop the cmake build system on Windows. Use the official build with conda posix package instead of cygwin.
This fixes #37 

~~I built successfully locally but got some issue depending on the python version (some mix with the python installed with conda and the host env). This MR is to test the build on conda-forge.~~

I had to:
- replace `/manifest` with `-manifest` and `DUMPBIN.EXE /SYMBOLS` with `DUMPBIN.EXE -SYMBOLS`, otherwise the `/` is replaced by the conda env path (is it because of the `ROOT` env variable set to that path?).
- change the path of `sort`
- changed the DLL name (`compiler_version_suffix` empty and remove minor and patch from `SharedLibraryDllNameTemplate`) to keep the same name as in the previous build. I was hoping to make the build compatible but there has still issues. See below. If `max_pin='x.x'` is correct, we could have the minor version, but not the patch one.
- added `-MACHINE:X64` based on https://github.com/tango-controls/omniorb-windows-ci/blob/master/appveyor.yml

To build, we have to pass 2 variables (done in `bld.bat`):
- `PYTHONPATH`: windows style path to the host env python site packages
- `PYTHONPATHOMNI`: cygpath style python exe path (used in `config.mk`)

One issue is that the result isn't binary compatible with previous build... At least cpptango needs to be re-compiled.
Trying to run an existing `TangoTest` with this new build raises: `The procedure entry point ??1TypeCode_member@CORBA@@QEAA@XZ could not be located in the dynamic link library tango.dll`.
After recompiling cpptango, I could run TangoTest without recompiling the binary.

I see 2 options:
- If we don't want to break compatibility, we apply this change only on omniORB 4.3. We have to wait for [cpptango support](https://gitlab.com/tango-controls/cppTango/-/issues/760) to use it.
- Merge this and rebuild cpptango. If people install last build from cpptango and omniorb, no pb. If they update cpptango without omniorb (or omniorb without cpptango), that will break their env.

Looking at packages who need `omniorb` or `omniorb-libs` on Windows, only `cpptango` should be impacted.

<details>
  <summary>See output</summary>

```
$ CONDA_SUBDIR=win-64 mamba repoquery  whoneeds -c conda-forge omniorb
No entries matching "omniorb" found

$ CONDA_SUBDIR=win-64 mamba repoquery  whoneeds -c conda-forge omniorb-libs
 Name                 Version Build           Depends                       Channel
───────────────────────────────────────────────────────────────────────────────────────────────
 cpptango             9.3.5   h04899b1_0      omniorb-libs >=4.2.5,<4.3.0a0 conda-forge/win-64
 cpptango             9.3.5   h04899b1_1      omniorb-libs >=4.2.5,<4.3.0a0 conda-forge/win-64
 cpptango             9.4.0   h643942d_0      omniorb-libs >=4.2.5,<4.3.0a0 conda-forge/win-64
 cpptango             9.4.0   h643942d_1      omniorb-libs >=4.2.5,<4.3.0a0 conda-forge/win-64
 omniorb              4.2.4   py310h694bffd_6 omniorb-libs 4.2.4 hc7e8586_6 conda-forge/win-64
 omniorb              4.2.4   py310ha05212b_6 omniorb-libs 4.2.4 h8b1b97a_6 conda-forge/win-64
 omniorb              4.2.4   py37h04d2302_4  omniorb-libs 4.2.4 h8b1b97a_4 conda-forge/win-64
 omniorb              4.2.4   py37h04d2302_5  omniorb-libs 4.2.4 h8b1b97a_5 conda-forge/win-64
 omniorb              4.2.4   py37h04d2302_6  omniorb-libs 4.2.4 h8b1b97a_6 conda-forge/win-64
 omniorb              4.2.4   py37h265e445_5  omniorb-libs 4.2.4 hc7e8586_5 conda-forge/win-64
 omniorb              4.2.4   py37h265e445_6  omniorb-libs 4.2.4 hc7e8586_6 conda-forge/win-64
 omniorb              4.2.4   py38ha65041e_5  omniorb-libs 4.2.4 hc7e8586_5 conda-forge/win-64
 omniorb              4.2.4   py38ha65041e_6  omniorb-libs 4.2.4 hc7e8586_6 conda-forge/win-64
 omniorb              4.2.4   py38he5377a8_4  omniorb-libs 4.2.4 h8b1b97a_4 conda-forge/win-64
 omniorb              4.2.4   py38he5377a8_5  omniorb-libs 4.2.4 h8b1b97a_5 conda-forge/win-64
 omniorb              4.2.4   py38he5377a8_6  omniorb-libs 4.2.4 h8b1b97a_6 conda-forge/win-64
 omniorb              4.2.4   py39hb76b349_4  omniorb-libs 4.2.4 h8b1b97a_4 conda-forge/win-64
 omniorb              4.2.4   py39hb76b349_5  omniorb-libs 4.2.4 h8b1b97a_5 conda-forge/win-64
 omniorb              4.2.4   py39hb76b349_6  omniorb-libs 4.2.4 h8b1b97a_6 conda-forge/win-64
 omniorb              4.2.4   py39hf7b6eba_5  omniorb-libs 4.2.4 hc7e8586_5 conda-forge/win-64
 omniorb              4.2.4   py39hf7b6eba_6  omniorb-libs 4.2.4 hc7e8586_6 conda-forge/win-64
 omniorb              4.2.5   py310h281aaab_3 omniorb-libs 4.2.5 h27dd91c_3 conda-forge/win-64
 omniorb              4.2.5   py310h281aaab_4 omniorb-libs 4.2.5 h27dd91c_4 conda-forge/win-64
 omniorb              4.2.5   py310h694bffd_0 omniorb-libs 4.2.5 hc7e8586_0 conda-forge/win-64
 omniorb              4.2.5   py310h694bffd_1 omniorb-libs 4.2.5 hc7e8586_1 conda-forge/win-64
 omniorb              4.2.5   py310h694bffd_2 omniorb-libs 4.2.5 hc7e8586_2 conda-forge/win-64
 omniorb              4.2.5   py310ha05212b_0 omniorb-libs 4.2.5 h8b1b97a_0 conda-forge/win-64
 omniorb              4.2.5   py310ha05212b_1 omniorb-libs 4.2.5 h8b1b97a_1 conda-forge/win-64
 omniorb              4.2.5   py310ha05212b_2 omniorb-libs 4.2.5 h8b1b97a_2 conda-forge/win-64
 omniorb              4.2.5   py310he97f525_3 omniorb-libs 4.2.5 hb04206d_3 conda-forge/win-64
 omniorb              4.2.5   py310he97f525_4 omniorb-libs 4.2.5 hb04206d_4 conda-forge/win-64
 omniorb              4.2.5   py311h40cf3c0_3 omniorb-libs 4.2.5 h27dd91c_3 conda-forge/win-64
 omniorb              4.2.5   py311h40cf3c0_4 omniorb-libs 4.2.5 h27dd91c_4 conda-forge/win-64
 omniorb              4.2.5   py311haf4ec1b_3 omniorb-libs 4.2.5 hb04206d_3 conda-forge/win-64
 omniorb              4.2.5   py311haf4ec1b_4 omniorb-libs 4.2.5 hb04206d_4 conda-forge/win-64
 omniorb              4.2.5   py37h04d2302_0  omniorb-libs 4.2.5 h8b1b97a_0 conda-forge/win-64
 omniorb              4.2.5   py37h04d2302_1  omniorb-libs 4.2.5 h8b1b97a_1 conda-forge/win-64
 omniorb              4.2.5   py37h04d2302_2  omniorb-libs 4.2.5 h8b1b97a_2 conda-forge/win-64
 omniorb              4.2.5   py37h265e445_0  omniorb-libs 4.2.5 hc7e8586_0 conda-forge/win-64
 omniorb              4.2.5   py37h265e445_1  omniorb-libs 4.2.5 hc7e8586_1 conda-forge/win-64
 omniorb              4.2.5   py37h265e445_2  omniorb-libs 4.2.5 hc7e8586_2 conda-forge/win-64
 omniorb              4.2.5   py38h78b27f5_3  omniorb-libs 4.2.5 h27dd91c_3 conda-forge/win-64
 omniorb              4.2.5   py38h78b27f5_4  omniorb-libs 4.2.5 h27dd91c_4 conda-forge/win-64
 omniorb              4.2.5   py38ha1d5d2c_3  omniorb-libs 4.2.5 hb04206d_3 conda-forge/win-64
 omniorb              4.2.5   py38ha1d5d2c_4  omniorb-libs 4.2.5 hb04206d_4 conda-forge/win-64
 omniorb              4.2.5   py38ha65041e_0  omniorb-libs 4.2.5 hc7e8586_0 conda-forge/win-64
 omniorb              4.2.5   py38ha65041e_1  omniorb-libs 4.2.5 hc7e8586_1 conda-forge/win-64
 omniorb              4.2.5   py38ha65041e_2  omniorb-libs 4.2.5 hc7e8586_2 conda-forge/win-64
 omniorb              4.2.5   py38he5377a8_0  omniorb-libs 4.2.5 h8b1b97a_0 conda-forge/win-64
 omniorb              4.2.5   py38he5377a8_1  omniorb-libs 4.2.5 h8b1b97a_1 conda-forge/win-64
 omniorb              4.2.5   py38he5377a8_2  omniorb-libs 4.2.5 h8b1b97a_2 conda-forge/win-64
 omniorb              4.2.5   py39h0a8b3da_3  omniorb-libs 4.2.5 h27dd91c_3 conda-forge/win-64
 omniorb              4.2.5   py39h0a8b3da_4  omniorb-libs 4.2.5 h27dd91c_4 conda-forge/win-64
 omniorb              4.2.5   py39ha00b111_3  omniorb-libs 4.2.5 hb04206d_3 conda-forge/win-64
 omniorb              4.2.5   py39ha00b111_4  omniorb-libs 4.2.5 hb04206d_4 conda-forge/win-64
 omniorb              4.2.5   py39hb76b349_0  omniorb-libs 4.2.5 h8b1b97a_0 conda-forge/win-64
 omniorb              4.2.5   py39hb76b349_1  omniorb-libs 4.2.5 h8b1b97a_1 conda-forge/win-64
 omniorb              4.2.5   py39hb76b349_2  omniorb-libs 4.2.5 h8b1b97a_2 conda-forge/win-64
 omniorb              4.2.5   py39hf7b6eba_0  omniorb-libs 4.2.5 hc7e8586_0 conda-forge/win-64
 omniorb              4.2.5   py39hf7b6eba_1  omniorb-libs 4.2.5 hc7e8586_1 conda-forge/win-64
 omniorb              4.2.5   py39hf7b6eba_2  omniorb-libs 4.2.5 hc7e8586_2 conda-forge/win-64
 pytango              9.3.3   py310ha1fa0db_3 omniorb-libs >=4.2.5,<4.3.0a0 conda-forge/win-64
 pytango              9.3.3   py37h4e464ee_3  omniorb-libs >=4.2.5,<4.3.0a0 conda-forge/win-64
 pytango              9.3.3   py38h6aad10e_3  omniorb-libs >=4.2.5,<4.3.0a0 conda-forge/win-64
 pytango              9.3.3   py39habe816b_3  omniorb-libs >=4.2.5,<4.3.0a0 conda-forge/win-64
 pytango              9.3.4   py310ha1fa0db_0 omniorb-libs >=4.2.5,<4.3.0a0 conda-forge/win-64
 pytango              9.3.4   py37h4e464ee_0  omniorb-libs >=4.2.5,<4.3.0a0 conda-forge/win-64
 pytango              9.3.4   py38h6aad10e_0  omniorb-libs >=4.2.5,<4.3.0a0 conda-forge/win-64
 pytango              9.3.4   py39habe816b_0  omniorb-libs >=4.2.5,<4.3.0a0 conda-forge/win-64
 pytango              9.3.5   py310h235ec21_0 omniorb-libs >=4.2.5,<4.3.0a0 conda-forge/win-64
 pytango              9.3.5   py310he5437e6_1 omniorb-libs >=4.2.5,<4.3.0a0 conda-forge/win-64
 pytango              9.3.5   py37h6b74a72_1  omniorb-libs >=4.2.5,<4.3.0a0 conda-forge/win-64
 pytango              9.3.5   py37ha060230_0  omniorb-libs >=4.2.5,<4.3.0a0 conda-forge/win-64
 pytango              9.3.5   py38hc387ade_1  omniorb-libs >=4.2.5,<4.3.0a0 conda-forge/win-64
 pytango              9.3.5   py38hfbcecd9_0  omniorb-libs >=4.2.5,<4.3.0a0 conda-forge/win-64
 pytango              9.3.5   py39h5a00035_0  omniorb-libs >=4.2.5,<4.3.0a0 conda-forge/win-64
 pytango              9.3.5   py39ha440df3_1  omniorb-libs >=4.2.5,<4.3.0a0 conda-forge/win-64
 pytango              9.3.6   py310h235ec21_0 omniorb-libs >=4.2.5,<4.3.0a0 conda-forge/win-64
 pytango              9.3.6   py37ha060230_0  omniorb-libs >=4.2.5,<4.3.0a0 conda-forge/win-64
 pytango              9.3.6   py38hfbcecd9_0  omniorb-libs >=4.2.5,<4.3.0a0 conda-forge/win-64
 pytango              9.3.6   py39h5a00035_0  omniorb-libs >=4.2.5,<4.3.0a0 conda-forge/win-64
 tango-test           3.4     h2d74725_1      omniorb-libs >=4.2.5,<4.3.0a0 conda-forge/win-64
 tango-test           3.4     h2d74725_2      omniorb-libs >=4.2.5,<4.3.0a0 conda-forge/win-64
 tango-test           3.5     h2d74725_0      omniorb-libs >=4.2.5,<4.3.0a0 conda-forge/win-64
 tango-test           3.6     h91493d7_0      omniorb-libs >=4.2.5,<4.3.0a0 conda-forge/win-64
 tango-test           3.6     h91493d7_1      omniorb-libs >=4.2.5,<4.3.0a0 conda-forge/win-64
 cpptango             9.3.6   h4b90b2b_0      omniorb-libs >=4.2.5,<4.3.0a0 conda-forge/win-64
 cpptango             9.4.1   h643942d_0      omniorb-libs >=4.2.5,<4.3.0a0 conda-forge/win-64
 cpptango             9.4.1   h7f68e99_1      omniorb-libs >=4.2.5,<4.3.0a0 conda-forge/win-64
 omniorb              4.2.5   py310h281aaab_5 omniorb-libs 4.2.5 h27dd91c_5 conda-forge/win-64
 omniorb              4.2.5   py311h40cf3c0_5 omniorb-libs 4.2.5 h27dd91c_5 conda-forge/win-64
 omniorb              4.2.5   py38h78b27f5_5  omniorb-libs 4.2.5 h27dd91c_5 conda-forge/win-64
 omniorb              4.2.5   py39h0a8b3da_5  omniorb-libs 4.2.5 h27dd91c_5 conda-forge/win-64
 pytango              9.4.0   py310hdd9df50_0 omniorb-libs >=4.2.5,<4.3.0a0 conda-forge/win-64
 pytango              9.4.0   py311h44fd347_0 omniorb-libs >=4.2.5,<4.3.0a0 conda-forge/win-64
 pytango              9.4.0   py38h07a3158_0  omniorb-libs >=4.2.5,<4.3.0a0 conda-forge/win-64
 pytango              9.4.0   py39h191c697_0  omniorb-libs >=4.2.5,<4.3.0a0 conda-forge/win-64
 pytango              9.4.1   py310hdd9df50_0 omniorb-libs >=4.2.5,<4.3.0a0 conda-forge/win-64
 pytango              9.4.1   py311h44fd347_0 omniorb-libs >=4.2.5,<4.3.0a0 conda-forge/win-64
 pytango              9.4.1   py38h07a3158_0  omniorb-libs >=4.2.5,<4.3.0a0 conda-forge/win-64
 pytango              9.4.1   py39h191c697_0  omniorb-libs >=4.2.5,<4.3.0a0 conda-forge/win-64
 tango-access-control 2.19    h38ca5f0_0      omniorb-libs >=4.2.5,<4.3.0a0 conda-forge/win-64
 tango-access-control 2.19    h406b9cd_0      omniorb-libs >=4.2.5,<4.3.0a0 conda-forge/win-64
 tango-database       5.21    h38ca5f0_0      omniorb-libs >=4.2.5,<4.3.0a0 conda-forge/win-64
 tango-database       5.21    h406b9cd_0      omniorb-libs >=4.2.5,<4.3.0a0 conda-forge/win-64
 tango-test           3.7     h38ca5f0_0      omniorb-libs >=4.2.5,<4.3.0a0 conda-forge/win-64
 tango-test           3.7     h406b9cd_0      omniorb-libs >=4.2.5,<4.3.0a0 conda-forge/win-64
```
</details>

### CODE REVIEW

**Comment by beenje** [comment]
@conda-forge-admin, please rerender

**Comment by beenje** [comment]
Only Python 3.11 build succeeded on Windows... Other failed with:

```

../../../bin/x86_win32/oidlwrapper.exe -gnuwin32 -T -bcxx -Wbh=.hh -Wbs=SK.cc -p../../../src/lib/omniORB/python3 -I../../../idl -Wbdebug -Wba -p../../../src/lib/omniORB/python3 -I../../../idl -Wbdebug -v -ComniORB4 ../../../idl/Naming.idl
Python path configuration:
  PYTHONHOME = (not set)
  PYTHONPATH = 'D:\bld\omniorb_1681904925966\_h_env;'
  program name = 'python'
  isolated = 0
  environment = 1
  user site = 0
  import site = 1
  sys._base_executable = 'D:\\bld\\omniorb_1681904925966\\work\\bin\\x86_win32\\omniidl.exe'
  sys.base_prefix = 'D:\\bld\\omniorb_1681904925966\\_h_env'
  sys.base_exec_prefix = 'D:\\bld\\omniorb_1681904925966\\_h_env'
  sys.executable = 'D:\\bld\\omniorb_1681904925966\\work\\bin\\x86_win32\\omniidl.exe'
  sys.prefix = 'D:\\bld\\omniorb_1681904925966\\_h_env'
  sys.exec_prefix = 'D:\\bld\\omniorb_1681904925966\\_h_env'
  sys.path = [
    'D:\\bld\\omniorb_1681904925966\\_h_env',
    '',
    'D:\\bld\\omniorb_1681904925966\\_h_env\\python38.zip',
    'D:\\bld\\omniorb_1681904925966\\work\\bin\\x86_win32',
  ]
Fatal Python error: init_fs_encoding: failed to get the Python codec of the filesystem encoding
Python runtime state: core initialized
ModuleNotFoundError: No module named 'encodings'

Current thread 0x00000518 (most recent call first):
<no Python frame>
PYTHONPATH=%PREFIX%;
%SRC_DIR%\bin\x86_win32\omniidl -T -bcxx -Wbh=.hh -Wbs=SK.cc -p..\..\..\src\lib\omniORB\python3 -I..\..\..\idl -Wbdebug -Wba -p..\..\..\src\lib\omniORB\python3 -I..\..\..\idl -Wbdebug -v -ComniORB4 ..\..\..\idl\Naming.idl
make[2]: *** [omniORB4/Naming.hh] Error 1
```

Looks like some python path is missing... More debugging to do.

**Comment by t-b** [comment]
Regarding the ABI incompatibility. This is a problem which others should have as well or? What is the standard conda procedure? On linux you would go from package name `libabcd" to `libabcd1` and make `libabcd1` conflict with `libabcd` (very rough summary).

**Comment by beenje** [comment]
> Regarding the ABI incompatibility. This is a problem which others should have as well or? What is the standard conda procedure? On linux you would go from package name `libabcd" to `libabcd1`and make`libabcd1`conflict with`libabcd` (very rough summary).

conda handles that differently. In the recipe you specify how a package is compatible using:

```
      run_exports:
        - {{ pin_subpackage('omniorb-libs', max_pin='x.x') }}
```

`maxp_pin` could be `x` or `x.x.x` depending on the package.
`max_pin='x.x'` means that if you compile a package with omniorb-libs 4.2.5, it will add the run requirement `omniorb-libs >=4.2.5,<4.3.0a0`.

This is what we have today. If we switch to omniorb 4.3, there is no issue.
Problem here is that this PR introduces a new way to build omniorb that breaks ABI compatibility with the same version (just a different build number). It's not really supposed to happen.

**Comment by ajoubertza** [comment]
Great work, @beenje! 

I also think we should merge this and rebuild cpptango.  The `whoneeds` query shows that only cpptango is affected on Windows, and we (Tango Controls Community) want this issue fixed for Tango Controls on Windows.

**Comment by beenje** [comment]
Thanks for the feedback @t-b and @ajoubertza . Merging!

**Pull request merged**
